language: node_js
node_js:
- '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: gae
  keyfile: vidly-secret.json
  project: vidly-280513
  default: true
  on:
    all_branches: true
env:
  global:
    secure: kfz7vpYbqKSuGXMuGfeTWeYcfbwyFroCUgnqJy1rtBcd+OB6Ppaw8lP2iE16A5efcVzWdM68bvzqs+9XABD+KpfGmebJqQKbIgS8rF7jdN/ZEUdxGHRH99esXiu/JRYCFTLZwGSO2I66fpvKMCcwUuIpqiXoJk7NN/LgSxO9SMCHH86ifhtS/2DDdIiGs0FCk3FOOGQaZHuB/fZy3i5ia9YkWLpNY65/L9+HrbnbVQCGJTuB+Y8LDV/3GYb9/HSUXnxztYolqPEO8I6AUXjzL3NCOZEDukZVB2f0tgU+4x214xPpxZnCbpM4wvK4J2mqqE5zv/kNsiF20qi+rN6puC32OupdcuAv0Pg6PCSQ4VSwctwPM3sYyoZub82l3B0RPaVDxy4WPX9Gv9a2XmUmtAgSJlFaQXIIRrSj86bxk30ZA3kgsSCCl8TlUWtjs4EYQjNR1K6kAYrbnOqhJEgkyWthnMISfkqdmkhLOIyV7QdWK/tRuEaLP6+6YAUdFMLGv9H25KNrhjLDdykcuXGWy3LSPS7R0GSd2AdMeSTn004g5SDGEFBnnrRsBQaakvAKiuy+y90FS3m/RsZlE8T8ROottlxFN0mgcQtRM1Pa4img06itV2RDD5XFRXlfOBcSghvJ8hI9rtUvCqdXETO6gk9UnY0Depm/cOcFejK2GzM=
