language: node_js
node_js:
  - '12'
branches:
  only:
    - master
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm test
deploy:
  keyfile: vidly-secret.json.enc
  project: vidly-280513
  default: true
  on:
      all_branches: true
