language: node_js
node_js:
- '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  provider: gae
  keyfile: vidly-secret.json
  project: vidly-280513
  default: true
  on:
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_5dd9c4483e20_key -iv $encrypted_5dd9c4483e20_iv
  -in vidly-secret.json.enc -out vidly-secret.json -d
