name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test
  
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Google App Engine
      - uses: atRobertoFlores/gae_deploy_action@master
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          project_name: ${{ secrets.PROJECT_NAME }}
