name: Vidly CI CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test
    
    - name: Deploy App
      uses: claudiuri/deploy-gae-action@v1.2
      with:
       service-account:  ${{ secrets.SERVICE_ACCOUNT }}
       project-id: ${{ secrets.PROJECT_ID }}  
